version: "3"
services:
  redis:
    image: redis:latest
    container_name: redtetris-redis-prod
    ports:
      - "6379:6379"
    restart: always

  server:
    build:
      context: .
      dockerfile: .docker/server/Dockerfile
    container_name: redtetris-server-prod
    ports:
      - "3004:3004"
    environment:
      REDIS_HOST: redtetris-redis-prod
    restart: always
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./:/redtetris/server/
      - /redtetris/server/node_modules

  client:
    build:
      context: .
      dockerfile: .docker/client/Dockerfile.prod
      args:
        server_host: ${RT_SERVER_HOST}
    container_name: redtetris-client-prod
    ports:
      - "8000:80"
    environment:
      REACT_APP_SERVER_HOST: ${RT_SERVER_HOST}
    restart: always
