version: "3"
services:
  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    container_name: redtetris-redis-prod
    restart: always

  server:
    build:
      context: .
      dockerfile: .docker/server/Dockerfile
    container_name: redtetris-server-prod
    ports:
      - "3004:3004"
    environment:
      REDIS_HOST: redtetris-redis-prod
      REDIS_PORT: 6379
      REDIS_PASSWD: ${REDIS_PASSWD}
    restart: always
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./:/redtetris/server/
      - /redtetris/server/node_modules

  client:
    build:
      context: .
      dockerfile: .docker/client/Dockerfile.prod
    container_name: redtetris-client-prod
    ports:
      - "8000:80"
    restart: always
