version: '3'
services:
  server:
    build:
      context: .
      dockerfile: .docker/server/Dockerfile
    ports:
      - "3004:3004"
    container_name: redtetris-server
    volumes:
       - ./:/redtetris/server/
       - /redtetris/server/node_modules

  client:
    build:
      context: .
      dockerfile: .docker/client/Dockerfile
    ports:
      - "3000:3000"
    container_name: redtetris-client
    stdin_open: true
    volumes:
       - ./:/redtetris/client/
       - /redtetris/client/node_modules