name: Format

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "13.8"
      - name: Install modules
        run: npm install
      - name: Run format check
        run: npm run format-ci
#      - name: Commit changes
#        uses: stefanzweifel/git-auto-commit-action@v4.1.2
#        with:
#          commit_message: Apply formatting changes
#          branch: ${{ github.head_ref }}
