name: Jest

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  jest:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
    steps:
      - env:
          REACT_REDIS_HOST: redis
          REACT_REDIS_PORT: 6379
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.8"
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test-ci
      - name: Run coverage
        run: npm run coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
